// Code generated by go-swagger; DO NOT EDIT.

package secure_object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteSecureObjectOKCode is the HTTP code returned for type DeleteSecureObjectOK
const DeleteSecureObjectOKCode int = 200

/*DeleteSecureObjectOK Ok.

swagger:response deleteSecureObjectOK
*/
type DeleteSecureObjectOK struct {
}

// NewDeleteSecureObjectOK creates DeleteSecureObjectOK with default headers values
func NewDeleteSecureObjectOK() *DeleteSecureObjectOK {

	return &DeleteSecureObjectOK{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteSecureObjectBadRequestCode is the HTTP code returned for type DeleteSecureObjectBadRequest
const DeleteSecureObjectBadRequestCode int = 400

/*DeleteSecureObjectBadRequest Bad request.

swagger:response deleteSecureObjectBadRequest
*/
type DeleteSecureObjectBadRequest struct {
}

// NewDeleteSecureObjectBadRequest creates DeleteSecureObjectBadRequest with default headers values
func NewDeleteSecureObjectBadRequest() *DeleteSecureObjectBadRequest {

	return &DeleteSecureObjectBadRequest{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteSecureObjectUnauthorizedCode is the HTTP code returned for type DeleteSecureObjectUnauthorized
const DeleteSecureObjectUnauthorizedCode int = 401

/*DeleteSecureObjectUnauthorized Not authenticated.

swagger:response deleteSecureObjectUnauthorized
*/
type DeleteSecureObjectUnauthorized struct {
}

// NewDeleteSecureObjectUnauthorized creates DeleteSecureObjectUnauthorized with default headers values
func NewDeleteSecureObjectUnauthorized() *DeleteSecureObjectUnauthorized {

	return &DeleteSecureObjectUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteSecureObjectForbiddenCode is the HTTP code returned for type DeleteSecureObjectForbidden
const DeleteSecureObjectForbiddenCode int = 403

/*DeleteSecureObjectForbidden Forbidden.

swagger:response deleteSecureObjectForbidden
*/
type DeleteSecureObjectForbidden struct {
}

// NewDeleteSecureObjectForbidden creates DeleteSecureObjectForbidden with default headers values
func NewDeleteSecureObjectForbidden() *DeleteSecureObjectForbidden {

	return &DeleteSecureObjectForbidden{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteSecureObjectNotFoundCode is the HTTP code returned for type DeleteSecureObjectNotFound
const DeleteSecureObjectNotFoundCode int = 404

/*DeleteSecureObjectNotFound Object not found.

swagger:response deleteSecureObjectNotFound
*/
type DeleteSecureObjectNotFound struct {
}

// NewDeleteSecureObjectNotFound creates DeleteSecureObjectNotFound with default headers values
func NewDeleteSecureObjectNotFound() *DeleteSecureObjectNotFound {

	return &DeleteSecureObjectNotFound{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteSecureObjectInternalServerErrorCode is the HTTP code returned for type DeleteSecureObjectInternalServerError
const DeleteSecureObjectInternalServerErrorCode int = 500

/*DeleteSecureObjectInternalServerError Failed to delete object.

swagger:response deleteSecureObjectInternalServerError
*/
type DeleteSecureObjectInternalServerError struct {
}

// NewDeleteSecureObjectInternalServerError creates DeleteSecureObjectInternalServerError with default headers values
func NewDeleteSecureObjectInternalServerError() *DeleteSecureObjectInternalServerError {

	return &DeleteSecureObjectInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// DeleteSecureObjectServiceUnavailableCode is the HTTP code returned for type DeleteSecureObjectServiceUnavailable
const DeleteSecureObjectServiceUnavailableCode int = 503

/*DeleteSecureObjectServiceUnavailable Not available.

swagger:response deleteSecureObjectServiceUnavailable
*/
type DeleteSecureObjectServiceUnavailable struct {
}

// NewDeleteSecureObjectServiceUnavailable creates DeleteSecureObjectServiceUnavailable with default headers values
func NewDeleteSecureObjectServiceUnavailable() *DeleteSecureObjectServiceUnavailable {

	return &DeleteSecureObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *DeleteSecureObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
