// Code generated by go-swagger; DO NOT EDIT.

package secure_object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSecureObjectOKCode is the HTTP code returned for type GetSecureObjectOK
const GetSecureObjectOKCode int = 200

/*GetSecureObjectOK Ok.

swagger:response getSecureObjectOK
*/
type GetSecureObjectOK struct {

	/*
	  In: Body
	*/
	Payload *GetSecureObjectOKBody `json:"body,omitempty"`
}

// NewGetSecureObjectOK creates GetSecureObjectOK with default headers values
func NewGetSecureObjectOK() *GetSecureObjectOK {

	return &GetSecureObjectOK{}
}

// WithPayload adds the payload to the get secure object o k response
func (o *GetSecureObjectOK) WithPayload(payload *GetSecureObjectOKBody) *GetSecureObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get secure object o k response
func (o *GetSecureObjectOK) SetPayload(payload *GetSecureObjectOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSecureObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSecureObjectBadRequestCode is the HTTP code returned for type GetSecureObjectBadRequest
const GetSecureObjectBadRequestCode int = 400

/*GetSecureObjectBadRequest Bad request.

swagger:response getSecureObjectBadRequest
*/
type GetSecureObjectBadRequest struct {
}

// NewGetSecureObjectBadRequest creates GetSecureObjectBadRequest with default headers values
func NewGetSecureObjectBadRequest() *GetSecureObjectBadRequest {

	return &GetSecureObjectBadRequest{}
}

// WriteResponse to the client
func (o *GetSecureObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetSecureObjectUnauthorizedCode is the HTTP code returned for type GetSecureObjectUnauthorized
const GetSecureObjectUnauthorizedCode int = 401

/*GetSecureObjectUnauthorized Not authenticated.

swagger:response getSecureObjectUnauthorized
*/
type GetSecureObjectUnauthorized struct {
}

// NewGetSecureObjectUnauthorized creates GetSecureObjectUnauthorized with default headers values
func NewGetSecureObjectUnauthorized() *GetSecureObjectUnauthorized {

	return &GetSecureObjectUnauthorized{}
}

// WriteResponse to the client
func (o *GetSecureObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetSecureObjectForbiddenCode is the HTTP code returned for type GetSecureObjectForbidden
const GetSecureObjectForbiddenCode int = 403

/*GetSecureObjectForbidden Forbidden.

swagger:response getSecureObjectForbidden
*/
type GetSecureObjectForbidden struct {
}

// NewGetSecureObjectForbidden creates GetSecureObjectForbidden with default headers values
func NewGetSecureObjectForbidden() *GetSecureObjectForbidden {

	return &GetSecureObjectForbidden{}
}

// WriteResponse to the client
func (o *GetSecureObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetSecureObjectNotFoundCode is the HTTP code returned for type GetSecureObjectNotFound
const GetSecureObjectNotFoundCode int = 404

/*GetSecureObjectNotFound Object not found.

swagger:response getSecureObjectNotFound
*/
type GetSecureObjectNotFound struct {
}

// NewGetSecureObjectNotFound creates GetSecureObjectNotFound with default headers values
func NewGetSecureObjectNotFound() *GetSecureObjectNotFound {

	return &GetSecureObjectNotFound{}
}

// WriteResponse to the client
func (o *GetSecureObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetSecureObjectInternalServerErrorCode is the HTTP code returned for type GetSecureObjectInternalServerError
const GetSecureObjectInternalServerErrorCode int = 500

/*GetSecureObjectInternalServerError Failed to list groups.

swagger:response getSecureObjectInternalServerError
*/
type GetSecureObjectInternalServerError struct {
}

// NewGetSecureObjectInternalServerError creates GetSecureObjectInternalServerError with default headers values
func NewGetSecureObjectInternalServerError() *GetSecureObjectInternalServerError {

	return &GetSecureObjectInternalServerError{}
}

// WriteResponse to the client
func (o *GetSecureObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetSecureObjectServiceUnavailableCode is the HTTP code returned for type GetSecureObjectServiceUnavailable
const GetSecureObjectServiceUnavailableCode int = 503

/*GetSecureObjectServiceUnavailable Not available.

swagger:response getSecureObjectServiceUnavailable
*/
type GetSecureObjectServiceUnavailable struct {
}

// NewGetSecureObjectServiceUnavailable creates GetSecureObjectServiceUnavailable with default headers values
func NewGetSecureObjectServiceUnavailable() *GetSecureObjectServiceUnavailable {

	return &GetSecureObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetSecureObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
