// Code generated by go-swagger; DO NOT EDIT.

package secure_object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPutSecureObjectParams creates a new PutSecureObjectParams object
//
// There are no default values defined in the spec.
func NewPutSecureObjectParams() PutSecureObjectParams {

	return PutSecureObjectParams{}
}

// PutSecureObjectParams contains all the bound params for the put secure object operation
// typically these are obtained from a http.Request
//
// swagger:parameters putSecureObject
type PutSecureObjectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Bucket name.
	  Required: true
	  In: path
	*/
	Bucket string
	/*object content.
	  Required: true
	  In: body
	*/
	HTTPText string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutSecureObjectParams() beforehand.
func (o *PutSecureObjectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBucket, rhkBucket, _ := route.Params.GetOK("bucket")
	if err := o.bindBucket(rBucket, rhkBucket, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("httpText", "body", ""))
			} else {
				res = append(res, errors.NewParseError("httpText", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.HTTPText = body
		}
	} else {
		res = append(res, errors.Required("httpText", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBucket binds and validates parameter Bucket from path.
func (o *PutSecureObjectParams) bindBucket(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Bucket = raw

	return nil
}
