// Code generated by go-swagger; DO NOT EDIT.

package secure_object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutSecureObjectCreatedCode is the HTTP code returned for type PutSecureObjectCreated
const PutSecureObjectCreatedCode int = 201

/*PutSecureObjectCreated Ok.

swagger:response putSecureObjectCreated
*/
type PutSecureObjectCreated struct {

	/*
	  In: Body
	*/
	Payload *PutSecureObjectCreatedBody `json:"body,omitempty"`
}

// NewPutSecureObjectCreated creates PutSecureObjectCreated with default headers values
func NewPutSecureObjectCreated() *PutSecureObjectCreated {

	return &PutSecureObjectCreated{}
}

// WithPayload adds the payload to the put secure object created response
func (o *PutSecureObjectCreated) WithPayload(payload *PutSecureObjectCreatedBody) *PutSecureObjectCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put secure object created response
func (o *PutSecureObjectCreated) SetPayload(payload *PutSecureObjectCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutSecureObjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutSecureObjectBadRequestCode is the HTTP code returned for type PutSecureObjectBadRequest
const PutSecureObjectBadRequestCode int = 400

/*PutSecureObjectBadRequest Bad request.

swagger:response putSecureObjectBadRequest
*/
type PutSecureObjectBadRequest struct {
}

// NewPutSecureObjectBadRequest creates PutSecureObjectBadRequest with default headers values
func NewPutSecureObjectBadRequest() *PutSecureObjectBadRequest {

	return &PutSecureObjectBadRequest{}
}

// WriteResponse to the client
func (o *PutSecureObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PutSecureObjectUnauthorizedCode is the HTTP code returned for type PutSecureObjectUnauthorized
const PutSecureObjectUnauthorizedCode int = 401

/*PutSecureObjectUnauthorized Not authenticated.

swagger:response putSecureObjectUnauthorized
*/
type PutSecureObjectUnauthorized struct {
}

// NewPutSecureObjectUnauthorized creates PutSecureObjectUnauthorized with default headers values
func NewPutSecureObjectUnauthorized() *PutSecureObjectUnauthorized {

	return &PutSecureObjectUnauthorized{}
}

// WriteResponse to the client
func (o *PutSecureObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PutSecureObjectForbiddenCode is the HTTP code returned for type PutSecureObjectForbidden
const PutSecureObjectForbiddenCode int = 403

/*PutSecureObjectForbidden Forbidden.

swagger:response putSecureObjectForbidden
*/
type PutSecureObjectForbidden struct {
}

// NewPutSecureObjectForbidden creates PutSecureObjectForbidden with default headers values
func NewPutSecureObjectForbidden() *PutSecureObjectForbidden {

	return &PutSecureObjectForbidden{}
}

// WriteResponse to the client
func (o *PutSecureObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PutSecureObjectNotFoundCode is the HTTP code returned for type PutSecureObjectNotFound
const PutSecureObjectNotFoundCode int = 404

/*PutSecureObjectNotFound Object not found.

swagger:response putSecureObjectNotFound
*/
type PutSecureObjectNotFound struct {
}

// NewPutSecureObjectNotFound creates PutSecureObjectNotFound with default headers values
func NewPutSecureObjectNotFound() *PutSecureObjectNotFound {

	return &PutSecureObjectNotFound{}
}

// WriteResponse to the client
func (o *PutSecureObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PutSecureObjectInternalServerErrorCode is the HTTP code returned for type PutSecureObjectInternalServerError
const PutSecureObjectInternalServerErrorCode int = 500

/*PutSecureObjectInternalServerError Failed to put object.

swagger:response putSecureObjectInternalServerError
*/
type PutSecureObjectInternalServerError struct {
}

// NewPutSecureObjectInternalServerError creates PutSecureObjectInternalServerError with default headers values
func NewPutSecureObjectInternalServerError() *PutSecureObjectInternalServerError {

	return &PutSecureObjectInternalServerError{}
}

// WriteResponse to the client
func (o *PutSecureObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// PutSecureObjectServiceUnavailableCode is the HTTP code returned for type PutSecureObjectServiceUnavailable
const PutSecureObjectServiceUnavailableCode int = 503

/*PutSecureObjectServiceUnavailable Not available.

swagger:response putSecureObjectServiceUnavailable
*/
type PutSecureObjectServiceUnavailable struct {
}

// NewPutSecureObjectServiceUnavailable creates PutSecureObjectServiceUnavailable with default headers values
func NewPutSecureObjectServiceUnavailable() *PutSecureObjectServiceUnavailable {

	return &PutSecureObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutSecureObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
