// Code generated by go-swagger; DO NOT EDIT.

// Package restapi S3
//
//  This API is dedicated to store objects to a bucket.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//  Contact: Houssem Aloulou
//
//  Consumes:
//    - text/plain
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
