// Code generated by go-swagger; DO NOT EDIT.

package object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetObjectOKCode is the HTTP code returned for type GetObjectOK
const GetObjectOKCode int = 200

/*GetObjectOK Ok.

swagger:response getObjectOK
*/
type GetObjectOK struct {

	/*
	  In: Body
	*/
	Payload *GetObjectOKBody `json:"body,omitempty"`
}

// NewGetObjectOK creates GetObjectOK with default headers values
func NewGetObjectOK() *GetObjectOK {

	return &GetObjectOK{}
}

// WithPayload adds the payload to the get object o k response
func (o *GetObjectOK) WithPayload(payload *GetObjectOKBody) *GetObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object o k response
func (o *GetObjectOK) SetPayload(payload *GetObjectOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectBadRequestCode is the HTTP code returned for type GetObjectBadRequest
const GetObjectBadRequestCode int = 400

/*GetObjectBadRequest Bad request.

swagger:response getObjectBadRequest
*/
type GetObjectBadRequest struct {
}

// NewGetObjectBadRequest creates GetObjectBadRequest with default headers values
func NewGetObjectBadRequest() *GetObjectBadRequest {

	return &GetObjectBadRequest{}
}

// WriteResponse to the client
func (o *GetObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetObjectUnauthorizedCode is the HTTP code returned for type GetObjectUnauthorized
const GetObjectUnauthorizedCode int = 401

/*GetObjectUnauthorized Not authenticated.

swagger:response getObjectUnauthorized
*/
type GetObjectUnauthorized struct {
}

// NewGetObjectUnauthorized creates GetObjectUnauthorized with default headers values
func NewGetObjectUnauthorized() *GetObjectUnauthorized {

	return &GetObjectUnauthorized{}
}

// WriteResponse to the client
func (o *GetObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetObjectForbiddenCode is the HTTP code returned for type GetObjectForbidden
const GetObjectForbiddenCode int = 403

/*GetObjectForbidden Forbidden.

swagger:response getObjectForbidden
*/
type GetObjectForbidden struct {
}

// NewGetObjectForbidden creates GetObjectForbidden with default headers values
func NewGetObjectForbidden() *GetObjectForbidden {

	return &GetObjectForbidden{}
}

// WriteResponse to the client
func (o *GetObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetObjectNotFoundCode is the HTTP code returned for type GetObjectNotFound
const GetObjectNotFoundCode int = 404

/*GetObjectNotFound Object not found.

swagger:response getObjectNotFound
*/
type GetObjectNotFound struct {
}

// NewGetObjectNotFound creates GetObjectNotFound with default headers values
func NewGetObjectNotFound() *GetObjectNotFound {

	return &GetObjectNotFound{}
}

// WriteResponse to the client
func (o *GetObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetObjectInternalServerErrorCode is the HTTP code returned for type GetObjectInternalServerError
const GetObjectInternalServerErrorCode int = 500

/*GetObjectInternalServerError Failed to list groups.

swagger:response getObjectInternalServerError
*/
type GetObjectInternalServerError struct {
}

// NewGetObjectInternalServerError creates GetObjectInternalServerError with default headers values
func NewGetObjectInternalServerError() *GetObjectInternalServerError {

	return &GetObjectInternalServerError{}
}

// WriteResponse to the client
func (o *GetObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetObjectServiceUnavailableCode is the HTTP code returned for type GetObjectServiceUnavailable
const GetObjectServiceUnavailableCode int = 503

/*GetObjectServiceUnavailable Not available.

swagger:response getObjectServiceUnavailable
*/
type GetObjectServiceUnavailable struct {
}

// NewGetObjectServiceUnavailable creates GetObjectServiceUnavailable with default headers values
func NewGetObjectServiceUnavailable() *GetObjectServiceUnavailable {

	return &GetObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
