// Code generated by go-swagger; DO NOT EDIT.

package object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutObjectCreatedCode is the HTTP code returned for type PutObjectCreated
const PutObjectCreatedCode int = 201

/*PutObjectCreated Ok.

swagger:response putObjectCreated
*/
type PutObjectCreated struct {

	/*
	  In: Body
	*/
	Payload *PutObjectCreatedBody `json:"body,omitempty"`
}

// NewPutObjectCreated creates PutObjectCreated with default headers values
func NewPutObjectCreated() *PutObjectCreated {

	return &PutObjectCreated{}
}

// WithPayload adds the payload to the put object created response
func (o *PutObjectCreated) WithPayload(payload *PutObjectCreatedBody) *PutObjectCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put object created response
func (o *PutObjectCreated) SetPayload(payload *PutObjectCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutObjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutObjectBadRequestCode is the HTTP code returned for type PutObjectBadRequest
const PutObjectBadRequestCode int = 400

/*PutObjectBadRequest Bad request.

swagger:response putObjectBadRequest
*/
type PutObjectBadRequest struct {
}

// NewPutObjectBadRequest creates PutObjectBadRequest with default headers values
func NewPutObjectBadRequest() *PutObjectBadRequest {

	return &PutObjectBadRequest{}
}

// WriteResponse to the client
func (o *PutObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PutObjectUnauthorizedCode is the HTTP code returned for type PutObjectUnauthorized
const PutObjectUnauthorizedCode int = 401

/*PutObjectUnauthorized Not authenticated.

swagger:response putObjectUnauthorized
*/
type PutObjectUnauthorized struct {
}

// NewPutObjectUnauthorized creates PutObjectUnauthorized with default headers values
func NewPutObjectUnauthorized() *PutObjectUnauthorized {

	return &PutObjectUnauthorized{}
}

// WriteResponse to the client
func (o *PutObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PutObjectForbiddenCode is the HTTP code returned for type PutObjectForbidden
const PutObjectForbiddenCode int = 403

/*PutObjectForbidden Forbidden.

swagger:response putObjectForbidden
*/
type PutObjectForbidden struct {
}

// NewPutObjectForbidden creates PutObjectForbidden with default headers values
func NewPutObjectForbidden() *PutObjectForbidden {

	return &PutObjectForbidden{}
}

// WriteResponse to the client
func (o *PutObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PutObjectNotFoundCode is the HTTP code returned for type PutObjectNotFound
const PutObjectNotFoundCode int = 404

/*PutObjectNotFound Object not found.

swagger:response putObjectNotFound
*/
type PutObjectNotFound struct {
}

// NewPutObjectNotFound creates PutObjectNotFound with default headers values
func NewPutObjectNotFound() *PutObjectNotFound {

	return &PutObjectNotFound{}
}

// WriteResponse to the client
func (o *PutObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PutObjectInternalServerErrorCode is the HTTP code returned for type PutObjectInternalServerError
const PutObjectInternalServerErrorCode int = 500

/*PutObjectInternalServerError Failed to put object.

swagger:response putObjectInternalServerError
*/
type PutObjectInternalServerError struct {
}

// NewPutObjectInternalServerError creates PutObjectInternalServerError with default headers values
func NewPutObjectInternalServerError() *PutObjectInternalServerError {

	return &PutObjectInternalServerError{}
}

// WriteResponse to the client
func (o *PutObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// PutObjectServiceUnavailableCode is the HTTP code returned for type PutObjectServiceUnavailable
const PutObjectServiceUnavailableCode int = 503

/*PutObjectServiceUnavailable Not available.

swagger:response putObjectServiceUnavailable
*/
type PutObjectServiceUnavailable struct {
}

// NewPutObjectServiceUnavailable creates PutObjectServiceUnavailable with default headers values
func NewPutObjectServiceUnavailable() *PutObjectServiceUnavailable {

	return &PutObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
