// Code generated by go-swagger; DO NOT EDIT.

package object_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateObjectCreatedCode is the HTTP code returned for type UpdateObjectCreated
const UpdateObjectCreatedCode int = 201

/*UpdateObjectCreated Ok.

swagger:response updateObjectCreated
*/
type UpdateObjectCreated struct {

	/*
	  In: Body
	*/
	Payload *UpdateObjectCreatedBody `json:"body,omitempty"`
}

// NewUpdateObjectCreated creates UpdateObjectCreated with default headers values
func NewUpdateObjectCreated() *UpdateObjectCreated {

	return &UpdateObjectCreated{}
}

// WithPayload adds the payload to the update object created response
func (o *UpdateObjectCreated) WithPayload(payload *UpdateObjectCreatedBody) *UpdateObjectCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update object created response
func (o *UpdateObjectCreated) SetPayload(payload *UpdateObjectCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateObjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateObjectBadRequestCode is the HTTP code returned for type UpdateObjectBadRequest
const UpdateObjectBadRequestCode int = 400

/*UpdateObjectBadRequest Bad request.

swagger:response updateObjectBadRequest
*/
type UpdateObjectBadRequest struct {
}

// NewUpdateObjectBadRequest creates UpdateObjectBadRequest with default headers values
func NewUpdateObjectBadRequest() *UpdateObjectBadRequest {

	return &UpdateObjectBadRequest{}
}

// WriteResponse to the client
func (o *UpdateObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateObjectUnauthorizedCode is the HTTP code returned for type UpdateObjectUnauthorized
const UpdateObjectUnauthorizedCode int = 401

/*UpdateObjectUnauthorized Not authenticated.

swagger:response updateObjectUnauthorized
*/
type UpdateObjectUnauthorized struct {
}

// NewUpdateObjectUnauthorized creates UpdateObjectUnauthorized with default headers values
func NewUpdateObjectUnauthorized() *UpdateObjectUnauthorized {

	return &UpdateObjectUnauthorized{}
}

// WriteResponse to the client
func (o *UpdateObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UpdateObjectForbiddenCode is the HTTP code returned for type UpdateObjectForbidden
const UpdateObjectForbiddenCode int = 403

/*UpdateObjectForbidden Forbidden.

swagger:response updateObjectForbidden
*/
type UpdateObjectForbidden struct {
}

// NewUpdateObjectForbidden creates UpdateObjectForbidden with default headers values
func NewUpdateObjectForbidden() *UpdateObjectForbidden {

	return &UpdateObjectForbidden{}
}

// WriteResponse to the client
func (o *UpdateObjectForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UpdateObjectNotFoundCode is the HTTP code returned for type UpdateObjectNotFound
const UpdateObjectNotFoundCode int = 404

/*UpdateObjectNotFound Object not found.

swagger:response updateObjectNotFound
*/
type UpdateObjectNotFound struct {
}

// NewUpdateObjectNotFound creates UpdateObjectNotFound with default headers values
func NewUpdateObjectNotFound() *UpdateObjectNotFound {

	return &UpdateObjectNotFound{}
}

// WriteResponse to the client
func (o *UpdateObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateObjectInternalServerErrorCode is the HTTP code returned for type UpdateObjectInternalServerError
const UpdateObjectInternalServerErrorCode int = 500

/*UpdateObjectInternalServerError Failed to put object.

swagger:response updateObjectInternalServerError
*/
type UpdateObjectInternalServerError struct {
}

// NewUpdateObjectInternalServerError creates UpdateObjectInternalServerError with default headers values
func NewUpdateObjectInternalServerError() *UpdateObjectInternalServerError {

	return &UpdateObjectInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// UpdateObjectServiceUnavailableCode is the HTTP code returned for type UpdateObjectServiceUnavailable
const UpdateObjectServiceUnavailableCode int = 503

/*UpdateObjectServiceUnavailable Not available.

swagger:response updateObjectServiceUnavailable
*/
type UpdateObjectServiceUnavailable struct {
}

// NewUpdateObjectServiceUnavailable creates UpdateObjectServiceUnavailable with default headers values
func NewUpdateObjectServiceUnavailable() *UpdateObjectServiceUnavailable {

	return &UpdateObjectServiceUnavailable{}
}

// WriteResponse to the client
func (o *UpdateObjectServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
